### ISSUE TITLE
3.0.0 planing

### ISSUE THREAD

**Issue by puzrin** [nodeca/pica#82]
- [x] API reqork, #84
- [x] Drop webgl support (unable to finish and maintain)
- [x] Promise interface
      - Should we keep callbacks? (i think not)
      - IE can require Promise polyfill (i think that's acceptable)
- [ ] ~~? 32-bit data store between convolvers, #35 (need more benchmarks)~~
- [x] Add `createImageBitmap()` support, #75
- [x] Webassembly support
      - convolvers ready, but give only 20% profit, because no SIMD support yet
      - unsharp should be ported (not difficult, but may need some rework, because gaussian blur is in separate package and may need webassembly port too)
      - passing wasm to webworkers needs investigation
- [x] Fix Chrome slowdown, #83
- [x] Reorganize code
      - filters generator should be in separate file
- [x] More cache, #81
- [x] Benchmarks rework.
      - need more granular testing
      - would be nice to run some tests in browser
- [x] `option.cancelToken`
